import React from "react";
import { Composition, Folder, Series, getStaticFiles, staticFile } from "remotion";
import { Audio } from "@remotion/media";
import { FPS, HEIGHT, SCENES, SceneId, TOTAL, WIDTH, sceneFrames } from "./timeline";
import { Opener } from "./scenes/Opener";
import { Ways } from "./scenes/Ways";
import { DoubleClick } from "./scenes/DoubleClick";
import { History } from "./scenes/History";
import { Glance } from "./scenes/Glance";
import { Gestures } from "./scenes/Gestures";
import { More } from "./scenes/More";
import { End } from "./scenes/End";

const COMPONENTS: Record<SceneId, React.FC> = { Opener, Ways, DoubleClick, History, Glance, Gestures, More, End };

// Hard cuts on the beat; each scene brings its own entrance. The soundtrack is generated by
// scripts/audio.ts from the same cue sheet (npm run audio).
export const Promo: React.FC = () => (
  <>
    <Series>
      {SCENES.map((s) => {
        const Scene = COMPONENTS[s.id];
        return (
          <Series.Sequence key={s.id} durationInFrames={sceneFrames(s.id)} name={s.id}>
            <Scene />
          </Series.Sequence>
        );
      })}
    </Series>
    {getStaticFiles().some((f) => f.name === "soundtrack.wav") ? <Audio src={staticFile("soundtrack.wav")} /> : null}
  </>
);

export const RemotionRoot: React.FC = () => (
  <>
    <Composition id="Promo" component={Promo} durationInFrames={TOTAL} fps={FPS} width={WIDTH} height={HEIGHT} />
    <Folder name="Scenes">
      {SCENES.map((s) => (
        <Composition key={s.id} id={s.id} component={COMPONENTS[s.id]} durationInFrames={sceneFrames(s.id)} fps={FPS} width={WIDTH} height={HEIGHT} />
      ))}
    </Folder>
  </>
);
