// 由 tools/privacy/make-privacy-page-source.py 从 tools/privacy/registry.json 生成；不要手改。
// current 行显示现有快照。planned 行也列出，值固定为「还没读」，真的读到再改登记状态。
import Foundation

struct WS2PrivacyRow: Sendable {
    let id: String
    let label: String
    /// public / sensitive / private：private 的值默认不展开。
    let sensitivity: String
    let group: String
    let reads: String
    let purpose: String
    let destination: String
    let activation: String
    let toggle: String
    /// current 或 planned。planned 的值固定是「还没读」。
    let status: String
    /// 登记表里这类读取用到的接口名；「显示技术细节」打开后才看得到。
    let interfaces: [String]
}

enum WS2PrivacyData {
    static let groupOrder: [String] = ["不用问就能读", "你同意后才读", "系统未公开的方法", "去了哪里"]

    static let rows: [WS2PrivacyRow] = [
        WS2PrivacyRow(
            id: "screen-shape",
            label: "屏幕和刘海的形状",
            sensitivity: "public",
            group: "不用问就能读",
            reads: "显示器编号、尺寸、菜单栏与安全区",
            purpose: "把控件放在所属屏幕",
            destination: "内存；不发送",
            activation: "布局启用时；隐私页仅取现有快照",
            toggle: "无独立开关，跟随刘海功能",
            status: "current",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "lock-state",
            label: "是否锁屏",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "锁定/未锁定/未知、当前控制台会话",
            purpose: "阻止锁屏时显示或执行敏感动作",
            destination: "内存；不发送",
            activation: "会话通知与授权边界复核",
            toggle: "安全边界不可单独关闭",
            status: "current",
            interfaces: ["CGSSessionScreenIsLocked", "CGSessionCopyCurrentDictionary"],
        ),
        WS2PrivacyRow(
            id: "battery",
            label: "配件电量",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "已连接配件型号、电量、连接状态",
            purpose: "显示现有配件状态",
            destination: "当前电量在内存；已提醒的低电状态保存在本机设置；不发送",
            activation: "现有活动来源；页面不再轮询",
            toggle: "配件电量开关",
            status: "current",
            interfaces: ["IOHIDManager", "IOServiceMatching"],
        ),
        WS2PrivacyRow(
            id: "recording-app",
            label: "哪个 App 在录音",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "音频进程标识、bundle ID、录音状态",
            purpose: "录音活动提示，不读取录音内容",
            destination: "内存；不发送",
            activation: "现有来源激活时",
            toggle: "实时活动",
            status: "current",
            interfaces: ["kAudioHardwarePropertyProcessObjectList"],
        ),
        WS2PrivacyRow(
            id: "window-ax",
            label: "窗口的标题、位置和大小",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "AX 标题、窗口ID、角色、几何、所属进程",
            purpose: "找到并收起或恢复目标窗口",
            destination: "内存；已收起窗口的恢复日志存本机",
            activation: "执行动作或既有缓存刷新",
            toggle: "辅助功能授权；关闭功能停止新增读取",
            status: "current",
            interfaces: ["AXUIElementCopyAttributeValue", "SLSOffscreenCheckProbe"],
        ),
        WS2PrivacyRow(
            id: "key-position",
            label: "按了哪个键",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "键码、修饰键、按下/松开、点击/滚动位置",
            purpose: "快捷键、惯用键和手势；不读输入文字",
            destination: "内存；不持久按键序列",
            activation: "功能启用且未锁定",
            toggle: "既有惯用键/手势开关；一直用Mac时关闭相应钩子",
            status: "current",
            interfaces: ["CGEvent.tapCreate"],
        ),
        WS2PrivacyRow(
            id: "window-image",
            label: "窗口的画面",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "授权目标窗口的像素帧与缩略图",
            purpose: "动画、预览和窗口浏览",
            destination: "目标为仅内存；磁盘行为待P1-FS验证",
            activation: "只有可见动画/预览",
            toggle: "屏幕录制授权；对应功能",
            status: "current",
            interfaces: ["SCScreenshotManager", "SCShareableContent", "SCStream"],
        ),
        WS2PrivacyRow(
            id: "camera-frame",
            label: "摄像头",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "临时视频帧、动作/是否有人结果",
            purpose: "用户触发的眨眼转头；离席检测另按L1合同；显式启用个人口令实验时，嘴部关键点用于本机模板匹配",
            destination: "只在内存；无主动上传；需真机文件检查；仅独立录入工具按指定路径导出嘴部关键点，不含图像",
            activation: "功能显式开启且当前状态允许",
            toggle: "摄像头及对应功能；锁屏不自动重开一般摄像头源",
            status: "current",
            interfaces: ["AVCaptureDevice", "AVCaptureSession", "VNDetectFaceLandmarksRequest"],
        ),
        WS2PrivacyRow(
            id: "music",
            label: "正在播放的歌",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "曲目、艺人、封面入口、进度、播放状态",
            purpose: "显示音乐并控制本次暂停的播放器",
            destination: "进程间自动化；内存；不把标题写日志",
            activation: "通知触发，现有兜底计时不在本轮更改",
            toggle: "实时活动/音乐控制和系统自动化授权",
            status: "current",
            interfaces: ["osascript"],
        ),
        WS2PrivacyRow(
            id: "notch-private",
            label: "刘海的精确轮廓",
            sensitivity: "public",
            group: "系统未公开的方法",
            reads: "bezelPath、轮廓和圆角数据",
            purpose: "贴合硬件边缘",
            destination: "内存",
            activation: "显示变化时缓存",
            toggle: "关闭自适应外形用公开安全区",
            status: "current",
            interfaces: ["bezelPath"],
        ),
        WS2PrivacyRow(
            id: "spaces-private",
            label: "其他桌面和最小化窗口的画面",
            sensitivity: "private",
            group: "系统未公开的方法",
            reads: "私有窗口/Space关系、位置和透明度，以及可用的窗口像素",
            purpose: "已授权的跨桌面预览及窗口控制；枚举或控制调用不一定读取像素",
            destination: "内存；磁盘行为待验证",
            activation: "用户动作时",
            toggle: "私有截图退回公开可用窗口/关闭预览",
            status: "current",
            interfaces: ["CGSHWCaptureWindowList", "CGSMainConnectionID", "SLSCopyManagedDisplaySpaces", "SLSCopyManagedDisplaySpacesFunction", "SLSCopySpacesForWindows", "SLSCopySpacesForWindowsFunction", "SLSGetWindowAlpha", "SLSGetWindowAlphaFunction", "SLSHideSpaces", "SLSMainConnectionID", "SLSMainConnectionIDFunction", "SLSManagedDisplay", "SLSManagedDisplayGetCurrentSpace", "SLSManagedDisplayGetCurrentSpaceFunction", "SLSManagedDisplaySetCurrentSpace", "SLSManagedDisplaySetCurrentSpaceFunction", "SLSMoveWindowWithGroup", "SLSMoveWindowWithGroupFunction", "SLSMoveWindowsToManagedSpace", "SLSMoveWindowsToManagedSpaceFunction", "SLSReassociateWindowsSpacesByGeometry", "SLSReassociateWindowsSpacesByGeometryFunction", "SLSRemoveWindowsFromSpaces", "SLSSetWindowAlpha", "SLSSetWindowAlphaFunction", "SLSShowSpaces", "SLSSpaceAddWindowsAndRemoveFromSpaces", "SLSSpaceCreate", "SLSSpaceSetAbsoluteLevel"],
        ),
        WS2PrivacyRow(
            id: "hinge",
            label: "屏幕开合的角度",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "HID 铰链角度",
            purpose: "桌面开合效果",
            destination: "内存",
            activation: "现有运动分档采样，锁屏按现有边界",
            toggle: "桌面开合",
            status: "current",
            interfaces: ["IOHIDDevice", "IOHIDDeviceClose", "IOHIDDeviceGetReport", "IOHIDDeviceOpen", "IOHIDManager", "IOHIDManagerActivate", "IOHIDManagerCancel", "IOHIDManagerClose", "IOHIDManagerCopyDevices", "IOHIDManagerCreate", "IOHIDManagerExtRelease", "IOHIDManagerOpen", "IOHIDManagerRegisterInputReportCallback", "IOHIDManagerSetDeviceMatching", "IOHIDManagerSetDispatchQueue"],
        ),
        WS2PrivacyRow(
            id: "tilt",
            label: "机身的倾斜",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "加速度计样本、移动状态",
            purpose: "桌面倾斜及铰链采样分档",
            destination: "内存",
            activation: "驱动推送，停用后拆回调",
            toggle: "倾斜效果",
            status: "current",
            interfaces: ["IOHIDDevice", "IOHIDManager", "IOHIDManagerActivate", "IOHIDManagerCancel", "IOHIDManagerClose", "IOHIDManagerCopyDevices", "IOHIDManagerCreate", "IOHIDManagerOpen", "IOHIDManagerRegisterInputReportCallback", "IOHIDManagerSetDeviceMatching", "IOHIDManagerSetDispatchQueue", "IOServiceMatching"],
        ),
        WS2PrivacyRow(
            id: "update",
            label: "检查更新",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "应用版本、Sparkle更新请求及服务端可见网络元数据",
            purpose: "取得更新目录和下载",
            destination: "更新服务；实际主机从构建配置和P2流量核验",
            activation: "仅自动更新开关或用户检查更新",
            toggle: "自动检查更新；关后仍可手动检查",
            status: "current",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "settings",
            label: "设置",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "本应用用户选择、已授权开关、模型槽位标识及被查询的系统偏好",
            purpose: "保留选择和适应当前系统设置",
            destination: "本机偏好文件；不存临时审批票据",
            activation: "原控制器需要查询时；页面只读已有快照",
            toggle: "各原有设置；重置只清本应用值",
            status: "current",
            interfaces: ["UserDefaults"],
        ),
        WS2PrivacyRow(
            id: "recovery",
            label: "恢复记录",
            sensitivity: "private",
            group: "去了哪里",
            reads: "收起窗口目标、标题和位置等恢复字段",
            purpose: "崩溃后放回用户窗口",
            destination: "本机 RecoveryJournal.plist；恢复后的删减需单独核验",
            activation: "收起/恢复事务",
            toggle: "无删除其他App数据行为",
            status: "current",
            interfaces: ["RecoveryJournal"],
        ),
        WS2PrivacyRow(
            id: "diagnostics",
            label: "运行记录",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "固定事件码、技术状态、耗时；禁止窗口标题和提示词",
            purpose: "排错与性能核验",
            destination: "本机专用目录0700/文件0600及一个备份",
            activation: "事件发生时；不开新轮询",
            toggle: "开发路径覆盖受同样安全规则限制",
            status: "current",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "login-item",
            label: "登录时自动启动",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "本应用登录项状态",
            purpose: "按用户选择启动",
            destination: "本机系统登录项服务",
            activation: "打开设置读取既有状态，修改时提交",
            toggle: "既有登录时自动启动",
            status: "current",
            interfaces: ["SMAppService"],
        ),
        WS2PrivacyRow(
            id: "agent-hooks",
            label: "编程助手的事件",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "provider、session/turn/tool/request ID、进程身份、状态及最小摘要",
            purpose: "A2把已选择助手的状态放到刘海",
            destination: "本机受保护IPC；不存完整hook输入；上游CLI自身可能联网",
            activation: "A2a/A2b用户启用后；先备份并合并配置",
            toggle: "编程助手活动；撤销只删除本应用配置块",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "conductor-ipc",
            label: "指挥连接",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "同账户对端凭据、项目/会话ID、单调序号、请求摘要",
            purpose: "D5a/b绑定输入与本机助手会话",
            destination: "Swift本机IPC；默认不监听局域网；跨设备传输另列下行",
            activation: "显式绑定，锁屏/睡眠/撤销关闭控制",
            toggle: "指挥模式及项目绑定",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "cross-device",
            label: "跨设备语音或控制",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "已配对对端身份、按键或音频流及认证握手",
            purpose: "明确选中的设备输入",
            destination: "可能经过本地网络/系统连续互通；实际路径须探针记录，不能称从不离开本机",
            activation: "显式选源并建立可信通道后",
            toggle: "来源选择和连接撤销",
            status: "planned",
            interfaces: ["NWConnection"],
        ),
        WS2PrivacyRow(
            id: "codex-server",
            label: "Codex 会话和审批",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "model/list能力、thread/turn/item状态、服务端审批请求、最小输入文本",
            purpose: "D6发送用户明确提交并显示真实回执",
            destination: "本机app-server；后续Codex服务调用可能上传用户提交给提供商",
            activation: "仅绑定会话；初次连接先snapshot",
            toggle: "指挥模式/会话绑定；不读取任意历史全文",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "speech-input",
            label: "语音输入",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "选定麦克风的音频、临时转写、所选识别器",
            purpose: "生成草稿，用户再次按播放才提交",
            destination: "默认本机识别；不具备本机识别则停用并说明，云路径必须另获同意",
            activation: "D1/D4有真实录音回执后，最长60秒",
            toggle: "麦克风来源；松手/取消即停止",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "bluetooth-presence",
            label: "随身设备是否在场",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "配对设备标识、明确连接/断开、被证实可读特征的请求回执、RSSI",
            purpose: "L2给L1离席和返回候选；RSSI不作身份授权",
            destination: "内存；不持久轨迹；设备名称不算可信身份",
            activation: "功能开启且蓝牙能力探针通过",
            toggle: "自动锁定/返回流程，停用拆监听",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "face-identity",
            label: "人脸特征与身份结果",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "已登记模板、活体挑战结果、匹配结果",
            purpose: "用户已批准的身份验证，Vision检测人脸不等于识别身份",
            destination: "模板仅保护存储；原帧不存；身份后端待F1/L3证明",
            activation: "身份功能实际可用且已启用时才显示本行",
            toggle: "刷脸功能及删除登记；不标成Face ID",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "unlock-secret",
            label: "解锁凭据",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "仅经用户明确建立的受保护系统凭据",
            purpose: "拟定锁屏返回后端；尚未证明可安全实现",
            destination: "必须Keychain/现有保护服务；不进日志/JSON/助手上下文",
            activation: "后端探针通过后另行启用；当前不得采集",
            toggle: "删除登记；无可用后端就不显示已支持",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "private-contact",
            label: "触控板和鼠标触点",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "设备句柄、触点ID、经实测换算的坐标/面积、帧时间",
            purpose: "I2给I1d点击和I1c拖动判定",
            destination: "内存当前接触组；不录制长期手势轨迹",
            activation: "符号、ABI、单位、停止回调均验证后",
            toggle: "输入增强；未知设备或ABI停用该路径",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "remote-hid",
            label: "遥控器按钮",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "I5a每设备HID page/usage、down/up、连接代次",
            purpose: "I1e/I1f在模式内映射动作",
            destination: "内存；映射归属账本仅本机",
            activation: "启用且已绑定来源；断线取消所有按键",
            toggle: "遥控器模式；退出恢复自己占用的映射",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "remote-touch",
            label: "遥控器触控区域",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "被探针证实的触控坐标与时间，不从普通键码臆造",
            purpose: "指挥模式轨迹输入",
            destination: "仅当前轨迹；最多2048采样点",
            activation: "I5a坐标来源探针通过后；无坐标仅按钮",
            toggle: "指挥模式",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "hid-remapping",
            label: "遥控器按键映射",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "hidutil当前映射和仅由本应用新增的条目",
            purpose: "I5b避免系统动作与本应用重复响应",
            destination: "本机系统映射；归属记录不含输入历史",
            activation: "用户开启时保存/差分应用，撤销差分恢复",
            toggle: "遥控器模式；不覆盖其他工具新增映射",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "game-controller",
            label: "手柄输入和反馈",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "已连接手柄ID、方向/按钮/触控输入、输出扳机阻力",
            purpose: "I8复用同一动作与交互租约",
            destination: "输入内存，反馈发回选定手柄；不跨会话缓存指令",
            activation: "显式功能开启，锁屏/断线/抢占立刻清扳机",
            toggle: "手柄输入；不抢全局无关控制器",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "authorization-key",
            label: "设备授权密钥",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "Secure Enclave 包裹的句柄、公钥、指纹集合状态摘要、一次性挑战及签名结果；不导出私钥",
            purpose: "用途和目标绑定的一次性授权账",
            destination: "~/Library/Application Support/WindowShade/Authorization/ 下的 device-key.v1、.pub、.biometry 文件及内存；当前源码没有把句柄写入 Keychain",
            activation: "每次明确授权；锁屏等推进代次",
            toggle: "删除登记；安全校验不可跳过",
            status: "current",
            interfaces: ["LAContext", "SecAccessControlCreateWithFlags", "SecureEnclave", "biometryState", "evaluatedPolicyDomainState", "stateHash"],
        ),
        WS2PrivacyRow(
            id: "agent-voice-proof",
            label: "审批口令和声纹辅助证据",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "一次随机口令的转写和辅助匹配结果",
            purpose: "D1高风险挑战的辅助证据；不是allow权限",
            destination: "短期内存；绑定请求摘要、代次、挑战ID；不写完整音频日志",
            activation: "已展示审批且新确认后才挑战",
            toggle: "不具备可靠声纹证明则用现有主身份路径",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "focus-preferences",
            label: "番茄钟的设置",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "专注时长（25/5 或 50/10）与「专注时收起聊天窗口」",
            purpose: "按你选的时长计时；收窗开关只在窗口所有权适配器就绪后生效",
            destination: "本机偏好；不发送",
            activation: "打开设置、改选项或开始计时时",
            toggle: "设置里的番茄钟两项",
            status: "current",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "focus-window-receipts",
            label: "番茄钟记下的窗口归属",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "收起的窗口 ID、进程、标题与代次，用于结束后核对再放回",
            purpose: "只放回这一轮确实由番茄钟动过的窗口",
            destination: "内存，仅当前一轮；不持久",
            activation: "窗口效果适配器就绪后",
            toggle: "跟随番茄钟；无适配器时不产生记录",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "command-review",
            label: "命令审批",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "完整命令、工作目录、会话上下文与一次性的审阅快照",
            purpose: "只允许这一条命令一次；文件与规则审批另立范围",
            destination: "本机原生认证与授权账；不写命令日志",
            activation: "owned 助手提出请求时；30 秒或断线即失效",
            toggle: "审批只在请求出现时；没有开关可以跳过授权",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "pair-verify-identity",
            label: "配对后的对端身份",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "已登记对端的公钥、revision 与本次连接的会话密钥",
            purpose: "只有这个身份能进入指挥控制",
            destination: "内存会话；Keychain 持久化仍缺",
            activation: "首次配对准入之后；撤销即关闭会话",
            toggle: "来源选择和连接撤销",
            status: "planned",
            interfaces: ["LAContext", "SecItemAdd", "SecItemCopyMatching", "SecItemUpdate"],
        ),
        WS2PrivacyRow(
            id: "input-scroll",
            label: "滚轮和鼠标按键",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "滚轮和鼠标按键（开了平滑滚动或改方向时才拦截；不存）",
            purpose: "按设置改滚动。这一包还没有确认过的滚轮，所以先不拦截",
            destination: "内存；不发送",
            activation: "平滑滚动或鼠标滚动方向打开，并且滚轮与逐事件来源都已确认",
            toggle: "平滑滚动、鼠标滚动方向",
            status: "planned",
            interfaces: ["CGEvent.tapCreate"],
        ),
        WS2PrivacyRow(
            id: "input-multitouch",
            label: "触控板上的手指",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "妙控鼠标、妙控板表面上的手指位置（开了轻点时才读；不存）",
            purpose: "三指轻点、四指轻点。结构还没核对，这一包不读",
            destination: "内存；不发送",
            activation: "主模型核对过多触点布局，并且对应开关打开",
            toggle: "三指轻点、四指轻点",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "input-siri-remote",
            label: "Siri 遥控器的按键",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "Siri 遥控器的按键。触控面和麦克风不在这一包",
            purpose: "遥控模式。静音映射还没核对，这一包不听",
            destination: "内存；不发送",
            activation: "遥控模式打开，并且静音映射已核对",
            toggle: "遥控模式",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "input-gamepad",
            label: "手柄",
            sensitivity: "public",
            group: "不用问就能读",
            reads: "手柄的按键、摇杆、触控板、陀螺仪（控制这台 Mac 开着时；游戏在前台时不读）",
            purpose: "用手柄操作这台 Mac。这一包没有接手柄",
            destination: "内存；不发送",
            activation: "每台手柄自己的开关打开之后",
            toggle: "控制这台 Mac",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "conductor-touch",
            label: "遥控器的触摸轨迹",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "遥控器触摸面上的轨迹。这一包不读，也不保存",
            purpose: "指挥时看这一笔。还没接遥控器",
            destination: "不读取",
            activation: "指挥模式打开并且遥控器已核对之后",
            toggle: "指挥模式",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "conductor-audio",
            label: "按住侧边按钮时的声音",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "按住侧边按钮时的声音。转写后丢弃。这一包不录",
            purpose: "松开后得到草稿。麦克风不在这一包",
            destination: "不读取",
            activation: "主模型接上麦克风之后，并且按住侧边按钮",
            toggle: "指挥模式",
            status: "planned",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "level-hud",
            label: "音量和亮度",
            sensitivity: "public",
            group: "不用问就能读",
            reads: "当前输出音量、指针所在屏幕亮度",
            purpose: "在刘海显示音量和亮度变化",
            destination: "内存；不发送",
            activation: "刘海提示启用时；音量监听变化，亮度每0.2秒读取",
            toggle: "跟随刘海功能",
            status: "current",
            interfaces: ["DisplayServicesGetBrightness"],
        ),
    ]
}
