#!/usr/bin/env python3
"""Independent srptools 1.0.1 client against the actual Swift/C server adapter.
No network or camera. Child pipes contain disposable test session keys; reports do not.
"""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path

import six
import srptools
from srptools import SRPClientSession, SRPContext, constants

assert srptools.VERSION == (1, 0, 1), "Pin srptools to 1.0.1"
assert six.__version__ == "1.17.0", "Pin six to 1.17.0"
PIN = "3939"  # Public test input, not a saved user credential.


class Server:
    def __init__(self, executable, convention):
        self.process = subprocess.Popen(
            [str(executable), "--test-json", "--m2", convention],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    def send(self, **fields):
        self.process.stdin.write(json.dumps(fields) + "\n")
        self.process.stdin.flush()
        line = self.process.stdout.readline()
        assert line, "native bridge ended unexpectedly"
        return json.loads(line)

    def close(self):
        self.process.stdin.close()
        self.process.wait(timeout=5)
        assert self.process.returncode == 0, self.process.stderr.read()
        self.process.stdout.close()
        self.process.stderr.close()


def client_for(reply, private, pin=PIN):
    context = SRPContext("Pair-Setup", pin, prime=constants.PRIME_3072,
                         generator=constants.PRIME_3072_GEN, hash_func=hashlib.sha512)
    client = SRPClientSession(context, private)
    client.process(reply["publicKey"], reply["salt"])
    return client


def unhex(value):
    return bytes.fromhex(value.decode() if isinstance(value, bytes) else value)


def good_session(executable, convention, private, report):
    server = Server(executable, convention)
    start = server.send(op="begin", pin=PIN)
    assert len(unhex(start["salt"])) == 16 and len(unhex(start["publicKey"])) == 384
    # SRPClientSession.process keeps salt bytes intact, including leading zeros.
    return server, start, client_for(start, private)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--bridge", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()
    report = {"srptools": "1.0.1", "six": "1.17.0", "cases": [],
              "salt_encoding": "raw 16 bytes",
              "hardware": "not_used", "production_integration": False}
    # Public deterministic edge fixture. a=1/A=5 is intentionally weak and is NEVER generated by the server.
    for private, label in [("01", "A=05 (383 leading zero bytes at width 384)"),
                           ("60975527035CF2AD1989806F0407210BC81EDC04E2762A56AFD529DDDA2D4393", "fixed 256-bit a")]:
        for convention in ["adk-padded", "srptools-minimal"]:
            server, start, client = good_session(args.bridge, convention, private, report)
            try:
                result = server.send(op="verify", publicKey=client.public, proof=client.key_proof.decode())
                assert "error" not in result, (label, convention, result)
                key = unhex(client.key)
                assert unhex(result["key"]) == key
                A = unhex(client.public)
                proof = unhex(client.key_proof)
                expected_minimal = hashlib.sha512(A + proof + key).hexdigest()
                expected_padded = hashlib.sha512(A.rjust(384, b"\0") + proof + key).hexdigest()
                expected = expected_padded if convention == "adk-padded" else expected_minimal
                assert result["serverProof"] == expected
                client_accepts = client.verify_proof(result["serverProof"].encode())
                assert client_accepts == (convention == "srptools-minimal" or len(A) == 384)
                assert server.send(op="verify", publicKey=client.public, proof=client.key_proof.decode()) == {"error": 1}
                report["cases"].append({"fixture": label, "mode": convention, "public_A_bytes": len(A),
                                         "native_key_matches_independent_client": True,
                                         "expected_M2_formula_matches": True,
                                         "raw_srptools_accepts_M2": client_accepts,
                                         "replay_rejected": True})
            finally:
                server.close()

    for name in ["wrong-pin", "wrong-proof", "A-zero", "A-N", "clear", "short-proof", "oversized-public"]:
        server, start, client = good_session(args.bridge, "srptools-minimal", "01", report)
        try:
            A, proof = client.public, client.key_proof.decode()
            expected = 4
            if name == "wrong-pin":
                client = client_for(start, "01", "0000")
                proof = client.key_proof.decode()
            elif name == "wrong-proof":
                mutated = bytearray(unhex(proof)); mutated[17] ^= 1; proof = mutated.hex()
            elif name == "A-zero": A, expected = "00", 2
            elif name == "A-N": A, expected = constants.PRIME_3072, 2
            elif name == "clear":
                assert server.send(op="clear") == {"cleared": True}
                assert server.send(op="clear") == {"cleared": True}
                expected = 1
            elif name == "short-proof": proof, expected = "00", 2
            elif name == "oversized-public": A, expected = "01" * 385, "malformed"
            assert server.send(op="verify", publicKey=A, proof=proof) == {"error": expected}, name
            assert server.send(op="verify", publicKey=client.public, proof=client.key_proof.decode()) == {"error": 1}, name
            report["cases"].append({"fixture": name, "rejected": True, "session_consumed": True})
        finally:
            server.close()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    print("Independent srptools client: 4 success/encoding cases + 7 rejection cases PASS")
    print("Confirmed difference: A=05 passes M1/K in both modes, but raw srptools rejects ADK padded M2; no mode selected implicitly")


if __name__ == "__main__":
    main()
